[package]
name = "SPL"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]

[dependencies]
naga = "0.11.0"
libc = "0.2"
log = "0.4"

[profile.release]
panic = 'abort'